

paramsHeihu:

  appKey: cli_1735194793846496
  appSecret: b4c45fa0f60e41de9769ba3055ce6ed4
  factoryNumber: 60894247

paramsErp:

  appKey: 1qxypOmr
  appSecret: 01E398317E2C2C634D90FA931EFFA92D
  certificate: OXYwHSWAc22UPHxfIUM0SV1t69Ur50h2hQ5rVnS47dYxfWu0mH2IbIxVNe/lcMG7/p6QHGOiUnFjDKwHLWdR8auh/DxDywljHbo9v0hwkP+bRbEM3DvXAezmhMmaRnD/mNus3y0pDHhpJiLJvZzlkqcBssBkw2+/3wH0wM5BoZYDSpcTyLzdRlBJ9O0hOuDf

file:
  token:
    filePath: /var/app/files/business/
    fileName: token-test.txt